/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package virtualpetgame;

/**
 *
 * @author phoeb
 */

import javax.swing.*;

public class GameplayFrameGUI extends javax.swing.JFrame {

    private final Animal pet;
    private final JLabel petImageLabel; //for displaying pet image
    
    
    /**
     * Creates new form GameGUI
     */
    public GameplayFrameGUI(Animal pet) {
        this.pet = pet;
        showWelcomeMessage(this.pet.getName());
        initComponents();
        
        //Set pet image
        petImageLabel = new JLabel();
        setPetImage();
        //Add petImageLabel to JPanel
        jPanel1.add(petImageLabel);
        petImageLabel.setBounds(10,10,100,100);
    }

    private void showWelcomeMessage(String petName) {
        JOptionPane.showMessageDialog(this, "Welcome to parenthood! You're now the owner of " + petName +
                "!\nRemember, " + petName + " has needs! Being a pet owner is a lot of work. Goodluck!",
                "Welcome!", JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Method to show a message dialog
    private void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Pet Message", JOptionPane.INFORMATION_MESSAGE);
    }
    
    //Method to set the pet image based on the type of animal it is
    private void setPetImage() {
        String imagePath;
        if(pet instanceof Cat) {
            imagePath = "/resources/cat.png";
        } else {
            imagePath = "/resources/dog.png";
        }
        //Set the icon of the pet image label
        petImageLabel.setIcon(new ImageIcon(imagePath));
    }

    // Method to update progress bars based on pet's current state
    private void updateProgressBars() {
        HungerBar.setValue(pet.getHunger());
        EnergyBar.setValue(pet.getEnergy());
        FunBar.setValue(pet.getFun());
        HygieneBar.setValue(pet.getHygiene());
        BladderBar.setValue(pet.getBladder());
        ThirstBar.setValue(pet.getThirst());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HungerBar = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EnergyBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        FunBar = new javax.swing.JProgressBar();
        HygieneBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        BladderBar = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        ThirstBar = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        feedButton = new javax.swing.JButton();
        waterButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        walkButton = new javax.swing.JButton();
        sleepButton = new javax.swing.JButton();
        toiletButton = new javax.swing.JButton();
        bathButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Virtual Pet Game");

        HungerBar.setBackground(new java.awt.Color(204, 204, 204));
        HungerBar.setValue(pet.getHunger());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Hunger:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Energy:");

        EnergyBar.setBackground(new java.awt.Color(204, 204, 204));
        EnergyBar.setValue(pet.getEnergy());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Fun:");

        FunBar.setBackground(new java.awt.Color(204, 204, 204));
        FunBar.setValue(pet.getFun());

        HygieneBar.setBackground(new java.awt.Color(204, 204, 204));
        HygieneBar.setValue(pet.getHygiene());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Hygiene:");

        BladderBar.setBackground(new java.awt.Color(204, 204, 204));
        BladderBar.setValue(pet.getBladder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Bladder:");

        ThirstBar.setBackground(new java.awt.Color(204, 204, 204));
        ThirstBar.setValue(pet.getThirst());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Thirst:");

        feedButton.setBackground(java.awt.Color.lightGray);
        feedButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feedButton.setForeground(new java.awt.Color(0, 0, 0));
        feedButton.setText("Feed");
        feedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedButtonActionPerformed(evt);
            }
        });

        waterButton.setBackground(java.awt.Color.lightGray);
        waterButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        waterButton.setForeground(new java.awt.Color(0, 0, 0));
        waterButton.setText("Fill Water Bowl");
        waterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterButtonActionPerformed(evt);
            }
        });

        playButton.setBackground(java.awt.Color.lightGray);
        playButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        playButton.setForeground(new java.awt.Color(0, 0, 0));
        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        walkButton.setBackground(java.awt.Color.lightGray);
        walkButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        walkButton.setForeground(new java.awt.Color(0, 0, 0));
        walkButton.setText("Walk");
        walkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkButtonActionPerformed(evt);
            }
        });

        sleepButton.setBackground(java.awt.Color.lightGray);
        sleepButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sleepButton.setForeground(new java.awt.Color(0, 0, 0));
        sleepButton.setText("Sleep");
        sleepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepButtonActionPerformed(evt);
            }
        });

        toiletButton.setBackground(java.awt.Color.lightGray);
        toiletButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        toiletButton.setForeground(new java.awt.Color(0, 0, 0));
        toiletButton.setText("Toilet");
        toiletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toiletButtonActionPerformed(evt);
            }
        });

        bathButton.setBackground(java.awt.Color.lightGray);
        bathButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bathButton.setForeground(new java.awt.Color(0, 0, 0));
        bathButton.setText("Bath");
        bathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bathButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(java.awt.Color.lightGray);
        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Save and Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText(pet.getName());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HungerBar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(EnergyBar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(FunBar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HygieneBar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(BladderBar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(ThirstBar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sleepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toiletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HungerBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnergyBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FunBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HygieneBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BladderBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThirstBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(feedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(waterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(walkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sleepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toiletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void feedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedButtonActionPerformed
        // TODO add your handling code here:
        if (pet.getHunger() > 60) {
            showMessage("Mmh, it seems like " + pet.getName() +
                    " is too full to eat right now. Try again later.");
        } else {
            pet.feed();
            showMessage(pet.getName() + " is now full!");
            updateProgressBars();
        }
    }//GEN-LAST:event_feedButtonActionPerformed

    private void waterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterButtonActionPerformed
        // TODO add your handling code here:
        if (pet.getThirst() > 60) {
            showMessage("Your pet is not thirsty. No need for water right now.");
        } else {
            pet.fillWaterBowl();
            showMessage(pet.getName() + " feels refreshed!");
            updateProgressBars();
        }
    }//GEN-LAST:event_waterButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        if (pet.getEnergy() < 20) {
            showMessage("Oh no! " + pet.getName() + " is too tired to play right now. Try "
                    + "letting " + pet.getName() + " get some rest first.");
        } else if (pet.getHunger() < 20) {
            showMessage("Oh no! " + pet.getName() + " is too hungry to play right now. Try "
                    + "feeding " + pet.getName() + " first.");
        } else if (pet.getBladder() < 20) {
            showMessage(pet.getName() + " needs to go to the toilet first before playing!");
        } else {
            pet.play();
            showMessage(pet.getName() + " had so much fun!");
            updateProgressBars();
        }
    }//GEN-LAST:event_playButtonActionPerformed

    private void walkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkButtonActionPerformed
        // TODO add your handling code here:
        if (pet.getEnergy() < 30) {
            showMessage("Oh no! " + pet.getName() + " is too tired to go for a walk right now. Try "
                    + "letting " + pet.getName() + " get some rest first.");
        } else if (pet.getHunger() < 20) {
            showMessage("Oh no! " + pet.getName() + " is too hungry right now. Try "
                    + "feeding " + pet.getName() + " first.");
        } else if (pet.getBladder() < 20) {
            showMessage(pet.getName() + " needs to go potty first!");
        } else {
            pet.walk();
            showMessage(pet.getName() + " likes going on walks with you!");
            updateProgressBars();
        }
    }//GEN-LAST:event_walkButtonActionPerformed

    private void sleepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepButtonActionPerformed
        // TODO add your handling code here:
        if (pet.getEnergy() > 40) {
            showMessage("Hmm, it seems like " + pet.getName() + " is not tired.");
        } else if (pet.getHunger() < 20) {
            showMessage("Oh no! " + pet.getName() + " is too hungry right now. Try "
                    + "feeding " + pet.getName() + " first.");
        } else if (pet.getBladder() < 20) {
            showMessage(pet.getName() + " needs to go potty first!");
        } else {
            pet.sleep();
            showMessage("ZZZZZZ... " + pet.getName() + " is sound asleep!");
            updateProgressBars();
        }
    }//GEN-LAST:event_sleepButtonActionPerformed

    private void toiletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toiletButtonActionPerformed
        // TODO add your handling code here:
        if (pet.getBladder() > 40) {
            showMessage("Mmh, it seems like " + pet.getName() +
                    " does not need to potty right now.");
        } else {
            pet.potty();
            showMessage(pet.getName() + " feels so much better.");
            updateProgressBars();
        }
    }//GEN-LAST:event_toiletButtonActionPerformed

    private void bathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bathButtonActionPerformed
        // TODO add your handling code here:
        pet.bathe();
        showMessage(pet.getName() + " is now squeaky clean!");
        updateProgressBars();
    }//GEN-LAST:event_bathButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        //Save pet to the database
        DatabaseSetup.saveNewPet(pet);
        
        showMessage("Pet saved successfully! Thank you for playing the game.");
        
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BladderBar;
    private javax.swing.JProgressBar EnergyBar;
    private javax.swing.JProgressBar FunBar;
    private javax.swing.JProgressBar HungerBar;
    private javax.swing.JProgressBar HygieneBar;
    private javax.swing.JProgressBar ThirstBar;
    private javax.swing.JButton bathButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton feedButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton playButton;
    private javax.swing.JButton sleepButton;
    private javax.swing.JButton toiletButton;
    private javax.swing.JButton walkButton;
    private javax.swing.JButton waterButton;
    // End of variables declaration//GEN-END:variables
}
